# name is optional, it will be displayed in the Actions menu
name: GHA - Demo #1
# on can be also a list [push, pull_request]
on: push
# each job is running on a different runner
# by default jobs run in parallel, until dependencies exist
jobs:
  Example-Action-1:
    name: Example Action #1
    runs-on: ubuntu-latest
    steps:
      # Display the event that triggered the workflow
      # "run" says that we are going to run a command
      # As any specific interpreter was defined, bash will be used here
      # ${{  }} defines, that here we have a command that needs to be interpreted
      # github is a context and event_name is one of the properties of the context
      - run: echo "The job was triggered by a ${{ github.event_name }} event."
      
      # Runner information
      # here a runner is a context of a runner and os contains information of OS that is used
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"
      
      # Information about the repository and branch
      # here we are using two next properties of github context
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      
      # Use Action located in https://github.com/actions
      # The action should have name, which will be displayed in the logs
      - name: Check out repository code
      # Here we use action checkout with the major version 2
        uses: actions/checkout@v2  
      
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      
      - run: echo "Your repository has been copied to the path ${{ github.workspace }} on the runner."
      
      - run: echo "The workflow is now ready to test your code on the runner."

      # A basic logic can be done if workflow file
      - name: conditional step when event name is pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: echo "This event is a pull request"

      # the | allows to write command in a new line, making the code more readable. 
      # When using | the newlines are preserved, when using > newlines are converted into spaces
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      # Action setup-dotnet installs dot.net
      # We can pass parameters to actions by using the "with" word. Here version 3 will be installed
      - name: Setup dotnet on runner
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      # This specific command uses the installed in the previous step software to document the version of dot.net
      - name: Display dotnet version
        run: dotnet --version

      # Runner has some tools preinstalled (cached). We can list it using runner context
      # We are going to display the folder name and in the next step list content of this folder
      - run: echo "The preinstalled tools are located here on the runner ${{ runner.tool_cache }}."
      
      - name: List files in tool cache
        run: |
          ls ${{ runner.tool_cache }}

      # Here we can check the status of the job using the job's context
      - run: echo "This job's status is ${{ job.status }}."

  # Another job is started on windows OS
  Second-Job:
    name: The second job running on another runner
    runs-on: windows-latest
    needs: Example-Action-1
    steps:
      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
