name: How to work with run
on: 
  push:
  workflow_dispatch:

jobs:
  job-1:
    name: Job to demonstate run command
    runs-on: ubuntu-latest
    steps:
      - name: Step to display PATH
        run: echo "The path on the runner is $PATH"
      - name: Step to display PATH - multiline 
        run: |
          echo "--------------------STARTING"
          echo "The path on the runner is $PATH"
          echo "--------------------FINISHING"
      
